server:
  port: 9002

spring:
  application:
    name: CUSTOMER-SERVICE
  
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/customer_db
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
